# Generated by Django 4.1.5 on 2023-02-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
